### ISSUE TITLE
fyi - ParseyMcParsefaceAPI

### ISSUE THREAD

**Issue by johndpope** [Undo1/ParseyParser#1]
I wondered if you might be interested in helping me build out a docker farm with microservices swift3 talking to grpc / Docker

I've got the foundations up and running - and saw your parser.
 https://github.com/johndpope/DockerParseyMcParsefaceAPI

I'm looking to do DCGAN with Parsey in swift.
https://github.com/bamos/dcgan-completion.tensorflow
like image completion but for text.

Eg. given a Stephen King trained data set - and entering the beginning texts
"the night was dark and ......"

It would auto complete in a king style manner. 

The server side grpc docker stuff is still in dev by google (was just released last night). 
Should be complete any day.

**Comment by Undo1** [comment]
That sounds really, really interesting, and I'll be sure to follow it. Not sure how much help I could be right now, though - most of my time is going into school (I'm 16) and some other projects.

I'll look into it, though. Thank you!
